import { ActionBlueprintGraphData } from '../types';

export const TEST_GRAPH_DATA: ActionBlueprintGraphData = {
  $schema: '',
  blueprint_id: 'b_1',
  blueprint_name: 'Test Blueprint',
  branches: [],
  edges: [
    {
      source: 'form-a',
      target: 'form-b',
    },
    {
      source: 'form-b',
      target: 'form-c',
    },
    {
      source: 'form-b',
      target: 'form-d',
    },
    {
      source: 'form-d',
      target: 'form-e',
    },
  ],
  forms: [
    {
      description: '',
      dynamic_field_config: {},
      field_schema: {
        properties: {},
        required: undefined,
        type: '',
      },
      id: 'f_1',
      is_resuable: false,
      name: 'test form',
    },
    {
      description: '',
      dynamic_field_config: {},
      field_schema: {
        properties: {},
        required: undefined,
        type: '',
      },
      id: 'f_2',
      is_resuable: false,
      name: 'test form',
    },
    {
      description: '',
      dynamic_field_config: {},
      field_schema: {
        properties: {},
        required: undefined,
        type: '',
      },
      id: 'f_3',
      is_resuable: false,
      name: 'test form',
    },
  ],
  nodes: [
    {
      data: {
        approval_auto_assign_config: undefined,
        approval_required: false,
        approval_roles: [],
        approval_scheduled_delay: undefined,
        approval_sla_duration: undefined,
        approval_task_name: undefined,
        auto_assign_config: undefined,
        component_id: 'f_1',
        component_key: 'form-a',
        component_type: 'form',
        data_promotion_config: undefined,
        id: 'n_a',
        input_mapping: {},
        name: 'Form A',
        permitted_roles: [],
        prerequisities: [],
        scheduled_delay: undefined,
        sla_duration: undefined,
        state_transition_rules: undefined,
      },
      id: 'form-a',
      position: {
        x: 0,
        y: 0,
      },
      type: 'form',
    },
    {
      data: {
        approval_auto_assign_config: undefined,
        approval_required: false,
        approval_roles: [],
        approval_scheduled_delay: undefined,
        approval_sla_duration: undefined,
        approval_task_name: undefined,
        auto_assign_config: undefined,
        component_id: 'f_1',
        component_key: 'form-b',
        component_type: 'form',
        data_promotion_config: undefined,
        id: 'n_b',
        input_mapping: {},
        name: 'Form B',
        permitted_roles: [],
        prerequisities: [],
        scheduled_delay: undefined,
        sla_duration: undefined,
        state_transition_rules: undefined,
      },
      id: 'form-b',
      position: {
        x: 0,
        y: 0,
      },
      type: 'form',
    },
    {
      data: {
        approval_auto_assign_config: undefined,
        approval_required: false,
        approval_roles: [],
        approval_scheduled_delay: undefined,
        approval_sla_duration: undefined,
        approval_task_name: undefined,
        auto_assign_config: undefined,
        component_id: 'f_2',
        component_key: 'form-c',
        component_type: 'form',
        data_promotion_config: undefined,
        id: 'n_c',
        input_mapping: {},
        name: 'Form C',
        permitted_roles: [],
        prerequisities: [],
        scheduled_delay: undefined,
        sla_duration: undefined,
        state_transition_rules: undefined,
      },
      id: 'form-c',
      position: {
        x: 0,
        y: 0,
      },
      type: 'form',
    },
    {
      data: {
        approval_auto_assign_config: undefined,
        approval_required: false,
        approval_roles: [],
        approval_scheduled_delay: undefined,
        approval_sla_duration: undefined,
        approval_task_name: undefined,
        auto_assign_config: undefined,
        component_id: 'f_2',
        component_key: 'form-d',
        component_type: 'form',
        data_promotion_config: undefined,
        id: 'n_d',
        input_mapping: {},
        name: 'Form D',
        permitted_roles: [],
        prerequisities: [],
        scheduled_delay: undefined,
        sla_duration: undefined,
        state_transition_rules: undefined,
      },
      id: 'form-d',
      position: {
        x: 0,
        y: 0,
      },
      type: 'form',
    },
    {
      data: {
        approval_auto_assign_config: undefined,
        approval_required: false,
        approval_roles: [],
        approval_scheduled_delay: undefined,
        approval_sla_duration: undefined,
        approval_task_name: undefined,
        auto_assign_config: undefined,
        component_id: 'f_3',
        component_key: 'form-e',
        component_type: 'form',
        data_promotion_config: undefined,
        id: 'n_e',
        input_mapping: {},
        name: 'Form E',
        permitted_roles: [],
        prerequisities: [],
        scheduled_delay: undefined,
        sla_duration: undefined,
        state_transition_rules: undefined,
      },
      id: 'form-e',
      position: {
        x: 0,
        y: 0,
      },
      type: 'form',
    },
  ],
  status: 'draft',
  tenant_id: '',
  triggers: [],
  version_id: '',
  version_notes: '',
  version_number: '',
};
